version = 1
# Two computer-generated files.
[[annotations]]
path = [
    "package-lock.json",
    "package.json",
    "tsconfig.json",
    "dist/index.js"
]
SPDX-FileCopyrightText =  "2025 The Linux Foundation"
SPDX-License-Identifier = "Apache-2.0"
